# Generated by Django 2.2.4 on 2019-08-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'SamplePermissions',
                'db_table': 'sample_permissions',
            },
        ),
        migrations.CreateModel(
            name='SampleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.SamplePermission')),
            ],
            options={
                'verbose_name_plural': 'SampleUsers',
                'db_table': 'sample_users',
            },
        ),
    ]
