version: '3'
services:
  app:
    build:
      context: .
      dockerfile: django_Dockerfile
    tty: true
    environment:
      DATABASE_HOST: rdb
    ports:
      - 8000:8000
    volumes:
      - ./src:/home/www
    depends_on:
      - rdb
  rdb:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: ddd_sample_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ddd_sample_db:/var/lib/postgresql/data
      - ./docker/rdb/initdb:/docker-entrypoint-initdb.d

volumes:
  ddd_sample_db: